import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  OneToMany,
  ManyToMany,
  JoinTable,
} from 'typeorm';
import { OrderItem } from '../../order/entities/order-item.entity';
import { CartItem } from '../../cart/entities/cart-item.entity';
import { Category } from '../../category/entities/category.entity';
import { Review } from '../../review/entities/review.entity';

@Entity('products')
export class Product {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  name: string;

  @Column({ type: 'text' })
  description: string;

  @Column({ type: 'decimal', precision: 10, scale: 2 })
  price: number;

  @Column({ default: 0 })
  stock: number;

  @ManyToMany(() => Category, (category) => category.products, { cascade: true })
  @JoinTable({
    name: 'product_categories',
    joinColumn: { name: 'product_id', referencedColumnName: 'id' },
    inverseJoinColumn: { name: 'category_id', referencedColumnName: 'id' },
  })
  categories: Category[];

  @Column('text', { array: true, default: '{}' })
  tags: string[];

  @Column('text', { array: true, default: '{}' })
  images: string[];

  @Column({ default: true })
  isActive: boolean;

  /**
   * pgvector column for AI-powered similarity search.
   * Stores vector embeddings generated by an external model.
   * Requires the pgvector extension to be enabled in PostgreSQL:
   *   CREATE EXTENSION IF NOT EXISTS vector;
   *
   * The column type 'vector(1536)' matches OpenAI's text-embedding-ada-002 dimension.
   * Adjust the dimension to match your chosen embedding model.
   */
  @Column({ type: 'float', array: true, nullable: true })
  embedding: number[];

  @OneToMany(() => OrderItem, (orderItem) => orderItem.product)
  orderItems: OrderItem[];

  @OneToMany(() => CartItem, (cartItem) => cartItem.product)
  cartItems: CartItem[];

  @OneToMany(() => Review, (review) => review.product)
  reviews: Review[];

  @Column({ type: 'decimal', precision: 3, scale: 2, default: 0 })
  averageRating: number;

  @Column({ default: 0 })
  reviewCount: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
